name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build Api Source 
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        
      - name: Build release for all modules
        run: ./gradlew shadowJar
      
      - name: dev.trindadedev.robokapi-all.jar
        uses: actions/upload-artifact@v4
        with:
          name: dev.trindadedev.robokapi-all
          path: build/libs/
      
      - name: Full Build Dir
        uses: actions/upload-artifact@v4
        with:
          name: full-build-dir
          path: build/